### ISSUE TITLE
"Delay" bug with FocusRing using focusTarget & ringTarget

### ISSUE THREAD

**Issue by waxandwane** [discord/focus-rings#3]
[Example CodeSandbox](https://codesandbox.io/s/ring-bug-pr4c7)

I have modified the Button component in the example to illustrate the bug, by wrapping the button element (the target of focus) in a div (the target of the ring) and providing both refs as props to FocusRing.

When selecting one of those buttons, the ring appears when the button loses focus instead of when it gains it, if no other element has gained focus in the meantime.

Steps to reproduce:
1. Click on one of the buttons
2. Click outside of the button (but not on another focusable element)

**Comment by faultyserver** [comment]
Fixed by #4
